name:                ffjson
version:             0.1.0.0
github:              "Sventimir/ffjson"
license:             BSD3
author:              "Sventimir"
maintainer:          "svantimir@gmail.com"
copyright:           "2022 Sventimir"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Command-line JSON filter and trans tool.

dependencies:
- base >= 4.7 && < 5
- exceptions
- megaparsec
- mtl
- text
- transformers

library:
  source-dirs: src

executables:
  ffjson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exceptions
    - ffjson
    - http-conduit
    - http-types

tests:
  ffjson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ffjson
    - containers
    - hspec
    - QuickCheck
