name:                ffjson
version:             1.0.0.0
github:              "Sventimir/ffjson"
license:             BSD3
author:              "Sventimir"
maintainer:          "svantimir@gmail.com"
copyright:           "2022 Sventimir"
category:            "command-line tools"
synopsis:            "A command-line tool for manipulating JSON data."

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A command-line tool for viewing, filtering and transforming JSON data. See README for more details.

dependencies:
- base >= 4.7 && < 5
- containers
- exceptions
- ListZipper
- megaparsec
- mtl
- text
- transformers

library:
  source-dirs: src

executables:
  ffjson:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - exceptions
    - ffjson
    - http-conduit
    - http-types

tests:
  ffjson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ffjson
    - containers
    - hspec
    - megaparsec
    - QuickCheck
